/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { Suspense, useEffect, useRef, useState } from 'react';
import { motion } from 'framer-motion-3d';
import {
  MeshDistortMaterial,
  MeshWobbleMaterial,
  useGLTF,
} from '@react-three/drei';
import { ThreeEvent, useFrame } from '@react-three/fiber';
import { Group } from 'three';
import { useBreakpointValue } from '@chakra-ui/react';
import { useMotionValue } from 'framer-motion';

export function SpaceModel({
  mousePosition,
}: {
  mousePosition: { x: number; y: number };
}) {
  const modelRef = useRef<Group | null>(null);
  const { nodes, materials }: any = useGLTF('/space-model.glb');

  useFrame(() => {
    if (modelRef.current) {
      modelRef.current.rotation.y = mousePosition.x * 0.1;
      modelRef.current.rotation.x = -mousePosition.y * 0.2;
      modelRef.current.rotation.z = mousePosition.x * 1;
    }
  });

  const positionX = useBreakpointValue([1, 1, 3]);

  return (
    <>
      <motion.mesh
        animate={{
          x: [0.1, 0.2, 0.1],
          y: [0.1, 0.2, 0.1],
          z: [0.1, 0.15, 0.1],
        }}
        transition={{
          duration: 5,
          repeat: Infinity,
        }}
      >
        <group dispose={null} >
          <group name="Scene">
            <group name="space-modelglb" userData={{ name: 'space-model.glb' }}>
              <group
                name="Sketchfab_model"
                rotation={[-1.5, -0.1, 6]}
                scale={0.3}
                userData={{ name: 'Sketchfab_model' }}
                position={[Number(positionX), 3, -7]}
              >
                <group name="root" userData={{ name: 'root' }} ref={modelRef}>
                  <group
                    name="GLTF_SceneRootNode"
                    rotation={[Math.PI / 2, 0, 0]}
                    userData={{ name: 'GLTF_SceneRootNode' }}
                  >
                    <group
                      name="Sphere_1"
                      position={[-0.39, -23.8, -0.43]}
                      rotation={[0, -Math.PI / 2, 0]}
                      scale={63.3}
                      userData={{ name: 'Sphere_1' }}
                    />
                    <group
                      name="Sphere001_3"
                      position={[-1.43, -3.2, -1.04]}
                      rotation={[0.15, -0.89, -0.07]}
                      scale={[47.44, 40.44, 50.62]}
                      userData={{ name: 'Sphere.001_3' }}
                    >
                      <mesh
                        name="mars"
                        castShadow
                        receiveShadow
                        geometry={nodes.mars.geometry}
                        material={materials.mars}
                        userData={{ name: 'Object_6' }}
                      />
                    </group>
                    <group
                      name="Cylinder_5"
                      position={[0, -0.77, 0]}
                      userData={{ name: 'Cylinder_5' }}
                    >
                      <mesh
                        name="Object_8"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_8.geometry}
                        material={materials.mars}
                        userData={{ name: 'Object_8' }}
                      />
                    </group>
                    <group
                      name="greengrass_tuft004_6"
                      position={[-6.34, -3.43, 4.28]}
                      rotation={[0.15, -0.31, 0.14]}
                      scale={[5.02, 3.6, 5.02]}
                      userData={{ name: 'greengrass_tuft.004_6' }}
                    >
                      <mesh
                        name="grass"
                        castShadow
                        receiveShadow
                        geometry={nodes.grass.geometry}
                        material={materials['Material.001']}
                        morphTargetDictionary={
                          nodes.grass.morphTargetDictionary
                        }
                        morphTargetInfluences={
                          nodes.grass.morphTargetInfluences
                        }
                        position={[0.01, 0.2, -0.5]}
                        userData={{ targetNames: ['0'], name: 'mesh_3' }}
                      >
                        <MeshWobbleMaterial
                          factor={0.01}
                          speed={10}
                          color="#003300"
                        />
                      </mesh>
                    </group>
                    <group
                      name="Cube003_7"
                      position={[-0.85, -0.43, 2.14]}
                      rotation={[-1.87, 0.7, 2.13]}
                      scale={[0.82, 0.72, 0.74]}
                      userData={{ name: 'Cube.003_7' }}
                    >
                      <mesh
                        name="Object_12"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_12.geometry}
                        material={materials.mars}
                        userData={{ name: 'Object_12' }}
                      />
                    </group>
                    <group
                      name="Cube017_8"
                      position={[1.19, -2.28, -5.32]}
                      rotation={[2.04, -1.22, 2.65]}
                      scale={[3.25, 4.22, 3.26]}
                      userData={{ name: 'Cube.017_8' }}
                    >
                      <mesh
                        name="Object_14"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_14.geometry}
                        material={materials.mars}
                        userData={{ name: 'Object_14' }}
                      />
                    </group>
                    <group
                      name="Cube018_9"
                      position={[1.77, -1.46, -3.42]}
                      rotation={[0.31, -0.18, 0.32]}
                      scale={[2.37, 2.36, 1.54]}
                      userData={{ name: 'Cube.018_9' }}
                    >
                      <mesh
                        name="Object_16"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_16.geometry}
                        material={materials.mars}
                        userData={{ name: 'Object_16' }}
                      />
                    </group>
                    <group
                      name="Cube019_10"
                      position={[-12.6, -2.75, -1.58]}
                      rotation={[0.73, 0.82, -0.15]}
                      scale={[2.37, 2.36, 1.54]}
                      userData={{ name: 'Cube.019_10' }}
                    >
                      <mesh
                        name="Object_18"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_18.geometry}
                        material={materials.mars}
                        userData={{ name: 'Object_18' }}
                      />
                    </group>
                    <group
                      name="Cube020_11"
                      position={[-5.32, -0.96, -5.73]}
                      rotation={[0.73, 0.77, -0.17]}
                      scale={[3.76, 3.73, 2.45]}
                      userData={{ name: 'Cube.020_11' }}
                    >
                      <mesh
                        name="Object_20"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_20.geometry}
                        material={materials.mars}
                        userData={{ name: 'Object_20' }}
                      />
                    </group>
                    <group
                      name="Cube021_12"
                      position={[-0.92, -0.77, -3.53]}
                      rotation={[0.83, -0.91, 1.14]}
                      scale={[2.37, 2.36, 1.54]}
                      userData={{ name: 'Cube.021_12' }}
                    >
                      <mesh
                        name="Object_22"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_22.geometry}
                        material={materials.mars}
                        userData={{ name: 'Object_22' }}
                      />
                    </group>
                    <group
                      name="Cube022_13"
                      position={[-3.82, -0.77, -3.32]}
                      rotation={[2.65, -0.29, -2.86]}
                      scale={[2.37, 2.36, 1.54]}
                      userData={{ name: 'Cube.022_13' }}
                    >
                      <mesh
                        name="Object_24"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_24.geometry}
                        material={materials.mars}
                        userData={{ name: 'Object_24' }}
                      />
                    </group>
                    <group
                      name="Cube023_14"
                      position={[2.88, -1.32, -0.86]}
                      rotation={[0.78, -1.28, 1.14]}
                      scale={[1.21, 1.2, 0.79]}
                      userData={{ name: 'Cube.023_14' }}
                    >
                      <mesh
                        name="Object_26"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_26.geometry}
                        material={materials.mars}
                        userData={{ name: 'Object_26' }}
                      />
                    </group>
                    <group
                      name="Cube024_15"
                      position={[-6.41, -1.48, 0.44]}
                      rotation={[2.79, -0.74, 2.94]}
                      scale={[1.85, 1.83, 1.2]}
                      userData={{ name: 'Cube.024_15' }}
                    >
                      <mesh
                        name="Object_28"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_28.geometry}
                        material={materials.mars}
                        userData={{ name: 'Object_28' }}
                      />
                    </group>
                    <group
                      name="Cube025_16"
                      position={[-3.88, -2.49, 3.98]}
                      rotation={[0.88, -1.03, 0.74]}
                      scale={[2.31, 2.29, 1.5]}
                      userData={{ name: 'Cube.025_16' }}
                    >
                      <mesh
                        name="Object_30"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_30.geometry}
                        material={materials.mars}
                        userData={{ name: 'Object_30' }}
                      />
                    </group>
                    <group
                      name="Cube026_17"
                      position={[4, -2.16, 0.99]}
                      rotation={[1.04, -0.99, 0.92]}
                      scale={[2.31, 2.29, 1.5]}
                      userData={{ name: 'Cube.026_17' }}
                    >
                      <mesh
                        name="Object_32"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_32.geometry}
                        material={materials.mars}
                        userData={{ name: 'Object_32' }}
                      />
                    </group>
                    <group
                      name="Cube027_18"
                      position={[-11.03, -2.13, -9.05]}
                      rotation={[2.37, 0.87, -2.07]}
                      scale={[5.02, 4.98, 3.26]}
                      userData={{ name: 'Cube.027_18' }}
                    >
                      <mesh
                        name="Object_34"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_34.geometry}
                        material={materials.mars}
                        userData={{ name: 'Object_34' }}
                      />
                    </group>
                    <group
                      name="Cube028_19"
                      position={[-10.29, -0.36, -19.86]}
                      rotation={[0.68, -0.4, 0.81]}
                      scale={[5.02, 4.98, 3.26]}
                      userData={{ name: 'Cube.028_19' }}
                    >
                      <mesh
                        name="Object_36"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_36.geometry}
                        material={materials.mars}
                        userData={{ name: 'Object_36' }}
                      />
                    </group>
                    <group
                      name="Icosphere_20"
                      position={[-1.27, -0.64, 2.57]}
                      rotation={[0.03, 0.44, 0.13]}
                      scale={[0.63, 0.55, 0.45]}
                      userData={{ name: 'Icosphere_20' }}
                    >
                      <mesh
                        name="fire"
                        castShadow
                        receiveShadow
                        geometry={nodes.fire.geometry}
                        material={materials.fire}
                        morphTargetDictionary={nodes.fire.morphTargetDictionary}
                        morphTargetInfluences={nodes.fire.morphTargetInfluences}
                        userData={{
                          targetNames: ['0', '1'],
                          name: 'mesh_17',
                        }}
                      >
                        {/* <MeshWobbleMaterial factor={4} speed={10} color="red" /> */}
                        <MeshDistortMaterial
                          distort={0.25}
                          speed={10}
                          color="orange"
                        />
                      </mesh>
                    </group>
                    <group
                      name="Cylinder001_21"
                      position={[-0.93, 0.54, 0.12]}
                      rotation={[0.75, 0.56, 0.19]}
                      userData={{ name: 'Cylinder.001_21' }}
                    >
                      <motion.mesh
                        name="stick"
                        castShadow
                        receiveShadow
                        geometry={nodes.stick.geometry}
                        material={materials.mars}
                        userData={{ name: 'Object_40' }}
                        animate={{
                          rotateX: [0, 1, 0, -0.7, 0],
                          //  rotateZ: [0, -1, -1, -1, 0]
                        }}
                        transition={{
                          duration: 5,
                          repeat: Infinity,
                        }}
                      />
                    </group>
                    <group
                      name="Cylinder002_22"
                      position={[-4.24, 1.92, -13.03]}
                      userData={{ name: 'Cylinder.002_22' }}
                    >
                      <mesh
                        name="smoke"
                        castShadow
                        receiveShadow
                        geometry={nodes.smoke.geometry}
                        material={materials.smoke}
                        morphTargetDictionary={
                          nodes.smoke.morphTargetDictionary
                        }
                        morphTargetInfluences={
                          nodes.smoke.morphTargetInfluences
                        }
                        userData={{ targetNames: ['0'], name: 'mesh_19' }}
                      >
                        <MeshWobbleMaterial
                          factor={0.01}
                          speed={10}
                          opacity={0.1}
                          transparent
                        />
                      </mesh>
                    </group>
                    {/* <group
                      name="Plane_24"
                      position={[-22.77, -25.08, -21.01]}
                      rotation={[0.61, -0.5, -0.99]}
                      scale={37.93}
                      userData={{ name: 'Plane_24' }}
                    >
                      <mesh
                        name="Object_44"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_44.geometry}
                        material={materials.spaceglow}
                        position={[-0.59, -0.01, -0.08]}
                        userData={{ name: 'Object_44' }}
                      />
                    </group> */}
                    <group
                      name="Armature_93"
                      position={[0, -0.73, 0]}
                      userData={{ name: 'Armature_93' }}
                    >
                      <group
                        name="GLTF_created_0"
                        userData={{ name: 'GLTF_created_0' }}
                      >
                        <primitive object={nodes.astronaut} />
                        <group name="arms_78" userData={{ name: 'arms_78' }} />
                        <group
                          name="backpack_79"
                          userData={{ name: 'backpack_79' }}
                        />
                        <group name="belt_80" userData={{ name: 'belt_80' }} />
                        <group
                          name="brows_81"
                          userData={{ name: 'brows_81' }}
                        />
                        <group name="eyes_82" userData={{ name: 'eyes_82' }} />
                        <group
                          name="glass_83"
                          userData={{ name: 'glass_83' }}
                        />
                        <group name="hair_84" userData={{ name: 'hair_84' }} />
                        <group name="head_85" userData={{ name: 'head_85' }} />
                        <group
                          name="head001_86"
                          userData={{ name: 'head.001_86' }}
                        />
                        <group
                          name="helmet_87"
                          userData={{ name: 'helmet_87' }}
                        />
                        <group
                          name="helmet001_88"
                          userData={{ name: 'helmet.001_88' }}
                        />
                        <group name="legs_89" userData={{ name: 'legs_89' }} />
                        <group name="neck_90" userData={{ name: 'neck_90' }} />
                        <group
                          name="scarf_91"
                          userData={{ name: 'scarf_91' }}
                        />
                        <group
                          name="torso_92"
                          userData={{ name: 'torso_92' }}
                        />
                        <skinnedMesh
                          name="Object_50"
                          geometry={nodes.Object_50.geometry}
                          material={materials.outline}
                          skeleton={nodes.Object_50.skeleton}
                          userData={{ name: 'Object_50' }}
                        />
                        <skinnedMesh
                          name="Object_55"
                          geometry={nodes.Object_55.geometry}
                          material={materials.outline}
                          skeleton={nodes.Object_55.skeleton}
                          userData={{ name: 'Object_55' }}
                        />
                        <skinnedMesh
                          name="Object_61"
                          geometry={nodes.Object_61.geometry}
                          material={materials['helmet.002']}
                          skeleton={nodes.Object_61.skeleton}
                          userData={{ name: 'Object_61' }}
                        />
                        <skinnedMesh
                          name="Object_64"
                          geometry={nodes.Object_64.geometry}
                          material={materials.outline}
                          skeleton={nodes.Object_64.skeleton}
                          userData={{ name: 'Object_64' }}
                        />
                        <skinnedMesh
                          name="Object_65"
                          geometry={nodes.Object_65.geometry}
                          material={materials['helmet.002']}
                          skeleton={nodes.Object_65.skeleton}
                          userData={{ name: 'Object_65' }}
                        />
                        <skinnedMesh
                          name="Object_72"
                          geometry={nodes.Object_72.geometry}
                          material={materials.outline}
                          skeleton={nodes.Object_72.skeleton}
                          userData={{ name: 'Object_72' }}
                        />
                        <skinnedMesh
                          name="Object_75"
                          geometry={nodes.Object_75.geometry}
                          material={materials.outline}
                          skeleton={nodes.Object_75.skeleton}
                          userData={{ name: 'Object_75' }}
                        />
                        <skinnedMesh
                          name="Object_78"
                          geometry={nodes.Object_78.geometry}
                          material={materials.outline}
                          skeleton={nodes.Object_78.skeleton}
                          userData={{ name: 'Object_78' }}
                        />
                        <skinnedMesh
                          name="Object_83"
                          geometry={nodes.Object_83.geometry}
                          material={materials.outline}
                          skeleton={nodes.Object_83.skeleton}
                          userData={{ name: 'Object_83' }}
                        />
                        <skinnedMesh
                          name="Object_86"
                          geometry={nodes.Object_86.geometry}
                          material={materials.outline}
                          skeleton={nodes.Object_86.skeleton}
                          userData={{ name: 'Object_86' }}
                        />
                        <skinnedMesh
                          name="Object_69"
                          geometry={nodes.Object_69.geometry}
                          material={materials.outline}
                          skeleton={nodes.Object_69.skeleton}
                          morphTargetDictionary={
                            nodes.Object_69.morphTargetDictionary
                          }
                          morphTargetInfluences={
                            nodes.Object_69.morphTargetInfluences
                          }
                          userData={{
                            targetNames: [
                              '0',
                              '1',
                              '2',
                              '3',
                              '4',
                              '5',
                              '6',
                              '7',
                            ],
                            name: 'Object_69',
                          }}
                        />
                        <skinnedMesh
                          name="Object_49"
                          geometry={nodes.Object_49.geometry}
                          material={materials.spaceame}
                          skeleton={nodes.Object_49.skeleton}
                          userData={{ name: 'Object_49' }}
                        />
                        <skinnedMesh
                          name="Object_52"
                          geometry={nodes.Object_52.geometry}
                          material={materials.spaceame}
                          skeleton={nodes.Object_52.skeleton}
                          userData={{ name: 'Object_52' }}
                        />
                        <skinnedMesh
                          name="Object_54"
                          geometry={nodes.Object_54.geometry}
                          material={materials.spaceame}
                          skeleton={nodes.Object_54.skeleton}
                          userData={{ name: 'Object_54' }}
                        />
                        <skinnedMesh
                          name="Object_57"
                          geometry={nodes.Object_57.geometry}
                          material={materials.spaceame}
                          skeleton={nodes.Object_57.skeleton}
                          morphTargetDictionary={
                            nodes.Object_57.morphTargetDictionary
                          }
                          morphTargetInfluences={
                            nodes.Object_57.morphTargetInfluences
                          }
                          userData={{
                            targetNames: ['0', '1', '2', '3', '4'],
                            name: 'Object_57',
                          }}
                        />
                        <skinnedMesh
                          name="Object_59"
                          geometry={nodes.Object_59.geometry}
                          material={materials.spaceame}
                          skeleton={nodes.Object_59.skeleton}
                          morphTargetDictionary={
                            nodes.Object_59.morphTargetDictionary
                          }
                          morphTargetInfluences={
                            nodes.Object_59.morphTargetInfluences
                          }
                          userData={{ targetNames: ['0'], name: 'Object_59' }}
                        />
                        <skinnedMesh
                          name="Object_63"
                          geometry={nodes.Object_63.geometry}
                          material={materials.spaceame}
                          skeleton={nodes.Object_63.skeleton}
                          userData={{ name: 'Object_63' }}
                        />
                        <skinnedMesh
                          name="Object_71"
                          geometry={nodes.Object_71.geometry}
                          material={materials.spaceame}
                          skeleton={nodes.Object_71.skeleton}
                          userData={{ name: 'Object_71' }}
                        />
                        <skinnedMesh
                          name="Object_74"
                          geometry={nodes.Object_74.geometry}
                          material={materials.spaceame}
                          skeleton={nodes.Object_74.skeleton}
                          userData={{ name: 'Object_74' }}
                        />
                        <skinnedMesh
                          name="Object_77"
                          geometry={nodes.Object_77.geometry}
                          material={materials.spaceame}
                          skeleton={nodes.Object_77.skeleton}
                          userData={{ name: 'Object_77' }}
                        />
                        <skinnedMesh
                          name="Object_80"
                          geometry={nodes.Object_80.geometry}
                          material={materials.spaceame}
                          skeleton={nodes.Object_80.skeleton}
                          userData={{ name: 'Object_80' }}
                        />
                        <skinnedMesh
                          name="Object_82"
                          geometry={nodes.Object_82.geometry}
                          material={materials.spaceame}
                          skeleton={nodes.Object_82.skeleton}
                          userData={{ name: 'Object_82' }}
                        />
                        <skinnedMesh
                          name="Object_85"
                          geometry={nodes.Object_85.geometry}
                          material={materials.spaceame}
                          skeleton={nodes.Object_85.skeleton}
                          userData={{ name: 'Object_85' }}
                        />
                        <skinnedMesh
                          name="Object_67"
                          geometry={nodes.Object_67.geometry}
                          material={materials.spaceameface}
                          skeleton={nodes.Object_67.skeleton}
                          morphTargetDictionary={
                            nodes.Object_67.morphTargetDictionary
                          }
                          morphTargetInfluences={
                            nodes.Object_67.morphTargetInfluences
                          }
                          userData={{
                            targetNames: [
                              '0',
                              '1',
                              '2',
                              '3',
                              '4',
                              '5',
                              '6',
                              '7',
                            ],
                            name: 'Object_67',
                          }}
                        />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
            
            <pointLight
              name="PointLight"
              intensity={1}
              decay={2}
              position={[-0.36, -0.29, 0.63]}
              userData={{ name: 'PointLight' }}
            />
            <directionalLight
              name="DirectionalLight"
              intensity={1}
              position={[-9.43, -0.01, 14.48]}
              userData={{ name: 'DirectionalLight' }}
            >
              <group position={[0, 0, -1]} />
            </directionalLight>
          </group>
        </group>
      </motion.mesh>
    </>
  );
}

useGLTF.preload('/space-model.glb');
